config/routes.rb
Kontakty::Application.routes.draw do
  resources :address_books

  get "home/index"

  root :to => "address_books#index"

end

app/models/address_book.rb
class AddressBook < ActiveRecord::Base
  validates :imie, :nazwisko, :format => { :with => /^[a-z]+$/i }, :presence => true
  validates :email, :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }, :presence => true, :uniqueness => true
end

app/controllers/address_books_controller.rb
class AddressBooksController < ApplicationController
  # GET /address_books
  # GET /address_books.xml
  def index
    @address_books = AddressBook.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @address_books }
    end
  end

  # GET /address_books/1
  # GET /address_books/1.xml
  def show
    @address_book = AddressBook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @address_book }
    end
  end

  # GET /address_books/new
  # GET /address_books/new.xml
  def new
    @address_book = AddressBook.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @address_book }
    end
  end

  # GET /address_books/1/edit
  def edit
    @address_book = AddressBook.find(params[:id])
  end

  # POST /address_books
  # POST /address_books.xml
  def create
    @address_book = AddressBook.new(params[:address_book])

    respond_to do |format|
      if @address_book.save
        format.html { redirect_to(@address_book, :notice => 'Address book was successfully created.') }
        format.xml  { render :xml => @address_book, :status => :created, :location => @address_book }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @address_book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /address_books/1
  # PUT /address_books/1.xml
  def update
    @address_book = AddressBook.find(params[:id])

    respond_to do |format|
      if @address_book.update_attributes(params[:address_book])
        format.html { redirect_to(@address_book, :notice => 'Address book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @address_book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /address_books/1
  # DELETE /address_books/1.xml
  def destroy
    @address_book = AddressBook.find(params[:id])
    @address_book.destroy

    respond_to do |format|
      format.html { redirect_to(address_books_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/address_books_helper.rb
module AddressBooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/address_books/_form.html.erb
<div id="wrapper">
  <div id="steps">
    <%= form_for @address_book, :html => { :id => "formElem" } do |f| %>
    
    <fieldset class="step">
      <legend>Krok 1.</legend>
      <p>
        <%= f.label :imie %><br />
        <%= f.text_field :imie %>
      </p>
      <p>
        <%= f.label :nazwisko %><br />
        <%= f.text_field :nazwisko %>
      </p>
    </fieldset>
    <fieldset class="step">
      <legend>Krok 2.</legend>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :www %><br />
        <%= f.text_field :www %>
      </p>
    </fieldset>
    <fieldset class="step">
      <legend>Krok 3.</legend>
      <p>
        <%= f.label :adres %><br />
        <%= f.text_field :adres %>
      </p>
    </fieldset>
    <fieldset class="step">
      <legend>Wyslij</legend>
      <p>
        <%= f.submit %>
      </p>
    </fieldset>
    <% end %>
  </div>
  <div id="navigation" style="display:none;">
    <ul>
      <li class="selected">
	<a href="#">Krok 1.</a>
      </li>
      <li>
	<a href="#">Krok 2.</a>
      </li>
      <li>
	<a href="#">Krok 3.</a>
      </li>
      <li>
	<a href="#">Wyslij</a>
      </li>
    </ul>
  </div>
</div>

app/views/address_books/edit.html.erb
<h1>Editing address_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_book %> |
<%= link_to 'Back', address_books_path %>

app/views/address_books/index.html.erb
<h1>Listing address_books</h1>

<table>
  <tr>
    <th>Imie</th>
    <th>Nazwisko</th>
    <th>Email</th>
    <th>Www</th>
    <th>Adres</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @address_books.each do |address_book| %>
  <tr>
    <td><%= address_book.imie %></td>
    <td><%= address_book.nazwisko %></td>
    <td><a href='mailto:'<%= address_book.email %>'><%= address_book.email %></a></td>
    <td><a href='<%= address_book.www %>'><%= address_book.www %></a></td>
    <td><%= address_book.adres %></td>
    <td><%= gravatar_image_tag(address_book.email.gsub('spam',
    'mdeering'), :alt => address_book.imie) %>
    <td><%= link_to 'Show', address_book %></td>
    <td><%= link_to 'Edit', edit_address_book_path(address_book) %></td>
    <td><%= link_to 'Destroy', address_book, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address book', new_address_book_path %>

app/views/address_books/new.html.erb
<h1>New address_book</h1>

<%= render 'form' %>

<%= link_to 'Back', address_books_path %>

app/views/address_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imie:</b>
  <%= @address_book.imie %>
</p>

<p>
  <b>Nazwisko:</b>
  <%= @address_book.nazwisko %>
</p>

<p>
  <b>Email:</b>
  <%= @address_book.email %>
</p>

<p>
  <b>Www:</b>
  <%= @address_book.www %>
</p>

<p>
  <b>Adres:</b>
  <%= @address_book.adres %>
</p>


<%= link_to 'Edit', edit_address_book_path(@address_book) %> |
<%= link_to 'Back', address_books_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1> <%= link_to "Książka adresowa", address_books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kontakty</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>